config/routes.rb
Blog::Application.routes.draw do

  devise_for :admins

  devise_for :users

  resources :tags

  resources :posts do
    resources :comments
  end

   root :to => "posts#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates_presence_of:comment
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tags
  has_many :comments
validates_presence_of:title
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

def after_sign_out_path_for(resource_or_scope)
    tags_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def new
    @post = Post.find(params[:post_id])
    @comment =Comment.new
end
  def create
    @post = Post.find(params[:post_id])
    if  @post.comments.create!(params[:comment])
   		redirect_to (posts_path)
	else
		render :action => "new"
	end

    
end
def index
@post = Post.find(params[:post_id])
@comment=@post.comments

end
def destroy
	@post = Post.find(params[:post_id])
	@comment = @post.comments.find(params[:id])
	@comment.destroy
	 respond_to do |format|
    	format.html {redirect_to @post}
	

     end	
end

end

app/controllers/passwords_controller.rb
class Devise::PasswordsController < ApplicationController
  prepend_before_filter :require_no_authentication
  include Devise::Controllers::InternalHelpers

  # GET /resource/password/new
  def new
    build_resource
    render_with_scope :new
  end

  # POST /resource/password
  def create
    self.resource = resource_class.send_reset_password_instructions(params[resource_name])

    if resource.errors.empty?
      set_flash_message :notice, :send_instructions
      redirect_to new_session_path(resource_name)
    else
      render_with_scope :new
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    self.resource = resource_class.new
    resource.reset_password_token = params[:reset_password_token]
    render_with_scope :edit
  end

  # PUT /resource/password
  def update
    self.resource = resource_class.reset_password_by_token(params[resource_name])

    if resource.errors.empty?
      set_flash_message :notice, :updated
      sign_in_and_redirect(resource_name, resource)
    else
      render_with_scope :edit
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_filter :authenticate_user!, :only => [:new, :create]
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])
    @tags = @post.tags
    @comments = @post.comments

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @tags = Tag.all
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @tags = Tag.all
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])
    @post.post_by=current_user.email

    respond_to do |format|
      if @post.save
        format.html {redirect_to(@post, :notice => 'Post was successfully created.') }
   
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    params[:post][:tag_ids] ||= []
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.xml
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.xml
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.xml
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.xml
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to(@tag, :notice => 'Tag was successfully created.') }
        format.xml  { render :xml => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.xml
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to(@tag, :notice => 'Tag was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.xml
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to(tags_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/comments/_comment.html.erb
  <div id="new">
<div  style="float: left; width: 400px;"><%= comment.comment %> </div>
<div style="float: left; width: 100px;">Posted by <%= comment.commentor %></div><br />
  </div><br />

app/views/comments/_form.html.erb
<%= form_for([@post,@post.comments.build]) do |f| %>
<div>
    <%= f.label :Name %><br /><br />
    <%= f.text_field :commentor %><br />
  </div><br />
  <div >
    <%= f.label :comment %><br /><br />
    <%= f.text_area :comment, :rows=>10 %><br />
  </div>
  <div ><br />
    <%= f.submit "Submit Comment" %>
  </div>
<% end %>

app/views/comments/_show.html.erb
  <div id="new">
    <%= comment.comment %> 
<br>
  </div>

app/views/comments/_showall.html.erb
<% @post.comments.each do |commen| %>
 <div id="new">
    <%= comment.comment %> 
<%= link_to "Destroy", [comment.post,comment], :method => :delete, :remote => true %><br>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
 <div class="post">
<h2 class="title"><%= @post.title %></h2>
</div>
<% @post.comments.each do |comment| %>

    <div class="post">
						
						<p class="meta"><span class="date"><%= comment.created_at.strftime("%b %d, %Y") %> </span><span class="posted">Posted by user</span></p>
						<div style="clear: both;">&nbsp;</div><br /> <br />
						<div class="entry">
							<p><%= comment.comment %></p>
							
						</div>
		</div>
<% end %>
<%= link_to 'Back', posts_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
<link href="style.css" rel="stylesheet" type="text/css" media="screen" />
</head>
<body>
<div id="wrapper">
	<div id="header-wrapper">
		<div id="header">
			<div id="logo">
				<h1>Postings</h1>
				<p> Welcome to our world</p>
			</div>
			<div id="menu">
				<ul>
					<li class="current_page_item"><%= link_to "Home", root_path %></li>
					<li><%= link_to "Sign up/ Sign in", new_post_path %></li>
					<li><%= link_to "New Post", new_post_path %></li>
					<li><a href="#">About</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</div>
		</div>
	</div>
	<!-- end #header -->
	<div id="page">
		<div id="page-bgtop">
			<div id="page-bgbtm">
				<div id="content">
					<%= yield %>
				
				
					<div style="clear: both;">&nbsp;</div>
				</div>

				<!-- end #content -->
				<div id="sidebar">
					<ul>
						<li>
							<div id="search" >
								<form method="get" action="#">
									<div>
										<input type="text" name="s" id="search-text" value="" />
										<input type="submit" id="search-submit" value="GO" />
									</div>
								</form>
							</div>
							<div style="clear: both;">&nbsp;</div>
						</li>
						<li>
							<h2>Kakinada</h2>
							<p>Kakinada is a city and a municipal corporation in East Godavari district in the Indian state of Andhra Pradesh. It is also the headquarters of East Godavari district.</p>
						</li>
						<li>
							<h2>Inkakinada</h2>
							<ul>
								<li><%= link_to 'Movies', "http://www.inkakinada.com/movies" %></li>
								<li><%= link_to 'Jobs', "http://www.inkakinada.com/jobs" %></li>
								<li><%= link_to 'Rent', "http://www.inkakinada.com/for-rent" %></li>
								<li><%= link_to 'Gifts', "http://www.inkakinada.com/gifts" %></li>
								<li><%= link_to 'Sale', "http://www.inkakinada.com/for-sale" %></li>
								<li><%= link_to 'Events', "http://www.inkakinada.com/events" %></li>
							</ul>
						</li>
						<li>
							<h2>Archives</h2>
							<ul>
								<li><a href="#">Aliquam libero</a></li>
								<li><a href="#">Consectetuer adipiscing elit</a></li>
								<li><a href="#">Metus aliquam pellentesque</a></li>
								<li><a href="#">Suspendisse iaculis mauris</a></li>
								<li><a href="#">Urnanet non molestie semper</a></li>
								<li><a href="#">Proin gravida orci porttitor</a></li>
							</ul>
						</li>
					</ul>
				</div>
				<!-- end #sidebar -->
				<div style="clear: both;">&nbsp;</div>
			</div>
		</div>
	</div>
	<!-- end #page -->
</div>
<div id="footer">
	<p>Copyright (c) 2011 postings.com. All rights reserved. </p>
</div>
<!-- end #footer -->
</body>

</html>

app/views/posts/_form.html.erb
<div class="post">
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"><br />
    <%= f.label :title %><br /><br />
    <%= f.text_field :title, :size => 50 %><br />
  </div>
  <div class="field"><br />
    <%= f.label :body %><br /><br />
    <%= f.text_area :body, :cols => 80, :rows => 20 %><br />
  </div>
  <div class="actions"><br />
    <%= f.submit %><br />
  </div>

    
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
	<% content_for :script do %>
		<%  current_user.email %>
	<% end %>
<% else %>
	<% content_for :script do %>
		<% "WELCOME" %>
	<% end %>
<% end %>



<% @posts.each do |post| %>
 <div class="post">
						<h2 class="title"><%= link_to "#{post.title}", post %></h2>
						<p class="meta"><span class="date"><%= post.created_at.strftime("%b %d, %Y") %> </span><span class="posted">Posted by Admin <%= post.post_by %></span></p>
						<div style="clear: both;">&nbsp;</div>
						<div class="entry">
							<p><%= post.body %></p>
							<p class="links"><%= link_to "Read More", post %>  &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Comments', post_comments_path(:post_id => post.id, :post => post, :method => :get) %> (<%= post.comments.count %>)</p>
						</div>
		</div>
<% end %>

app/views/posts/new.html.erb
<center>
<div id="user_nav">

  <% if user_signed_in? %>
	<% if current_user.email == "pvr@yahoo.com" %>
		<% current_user.update_attribute :admin, true %>
	<% end %>
	<%if  current_user.admin? %>
		<%= "ADMIN" %>
	<% end %>
	Signed in as <%= current_user.email %>. Not you?
    	<%= link_to "Sign out", destroy_user_session_path%>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>



<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</center>

app/views/posts/show(o).html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>



<h2>comments:</h2>

<div id="comments_add">
 
<% @post.comments.each do |commen| %>
<%= render :partial => "comments/show", :locals => {:comment => commen } %>
<% end %>
</div>


<br />

<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
<br />

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="post">
						<h2 class="title"><%= @post.title %></h2>
						<p class="meta"><span class="date"><%= @post.created_at.strftime("%b %d, %Y") %> </span><span class="posted">Posted by Admin <%= @post.post_by %></span></p>
						<div style="clear: both;">&nbsp;</div>
						<div class="entry">
<p><%= @post.body %></p>

<div id="comments_add">
<%= link_to "View Previous Comments", post_comments_path(@post), :remote => true %> <br /><br />
</div><br/><br/><div style="clear: both;">&nbsp;</div>


							
						
	<%= render "comments/form" %><br/>
<br />
 
<p class="links"><%= link_to "Back", posts_path %> </p>
</div>
		</div>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<%= "Sucessfully logged out" %><br />
<%= link_to "Back", posts_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @tag.description %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>